### ISSUE TITLE
Not working with DnD 5e version 2.2.2

### ISSUE THREAD

**Issue by Manngunner** [Drental/fvtt-tokenactionhud#426]
I can't get the mod to work with DnD5e versions newer than 2.1.5. One error seen:
```
Uncaught (in promise) TypeError: n.charAt is not a function
[Detected 1 package: token-action-hud]
    r bundle.min.js:1
    _getAbilityList bundle.min.js:1
    _buildAbilitiesCategory bundle.min.js:1
    _buildCategories bundle.min.js:1
    _buildSingleTokenList bundle.min.js:1
    doBuildActionList bundle.min.js:1
    buildActionList bundle.min.js:1
    updateHud bundle.min.js:1
    setTimeout handler*update bundle.min.js:1
    <anonymous> bundle.min.js:1
    #call foundry.js:724
    callAll foundry.js:681
    control foundry.js:25388
    _onClickLeft foundry.js:25610
    _onClickLeft foundry.js:47425
    callback foundry.js:27872
    _handleClickLeft foundry.js:28069
    _handleMouseDown foundry.js:28049
    emit index.js:181
    dispatchEvent interaction.min.mjs:8
    processPointerDown interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    recursiveFindHit interaction.min.mjs:8
    findHit interaction.min.mjs:8
    processInteractive interaction.min.mjs:8
    onPointerDown interaction.min.mjs:8
    addEvents interaction.min.mjs:8
    setTargetElement interaction.min.mjs:8
    r interaction.min.mjs:8
    initPlugins core.min.mjs:8
    r core.min.mjs:8
    create core.min.mjs:8
    ro core.min.mjs:8
    e app.min.mjs:8
    #createApplication foundry.js:23415
    initialize foundry.js:23317
    initializeCanvas foundry.js:8094
bundle.min.js:1:61357
```

Another error seen is:
```
Uncaught (in promise) TypeError: n.charAt is not a function
[Detected 1 package: token-action-hud]
    r https://<Hostname>:30000/modules/token-action-hud/scripts/bundle.min.js:1
    _getAbilityList https://<Hostname>:30000/modules/token-action-hud/scripts/bundle.min.js:1
    _buildAbilitiesCategory https://<Hostname>:30000/modules/token-action-hud/scripts/bundle.min.js:1
    _buildCategories https://<Hostname>:30000/modules/token-action-hud/scripts/bundle.min.js:1
bundle.min.js:1:61357
```

**Comment by Larkinabout** [comment]
Hi @Manngunner, support for D&D 5e has now moved to the dedicated [Token Action HUD D&D 5e](https://foundryvtt.com/packages/token-action-hud-dnd5e) module.
